name: Main

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  # The checking system is disabled for now
  # quality:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Check out
  #       uses: actions/checkout@v4

  #     - uses: actions/cache@v4
  #       with:
  #         path: ~/.cache/pre-commit
  #         key: pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}

  #     - name: Set up the environment
  #       uses: ./.github/actions/setup-env

  #     - name: Run checks
  #       run: make check

  check-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up the environment
        uses: ./.github/actions/setup-env

      - name: Install doc dependencies
        run: |
          uv sync --group docs

      - name: Check if documentation can be built
        run: |
          uv run mkdocs build -f docs/mkdocs.yml -d _build
